# Generated by Django 4.2.7 on 2023-11-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micrud', '0002_alter_equipos_nombreciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
