# Generated by Django 4.2.7 on 2023-11-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micrud', '0005_alter_equipos_numequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='nombreEquipo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
