# Generated by Django 4.2.7 on 2023-11-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_brand_brand_name_alter_brand_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
