# Generated by Django 5.0 on 2023-12-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nameStadium', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=5)),
                ('boxSize', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nameTeam', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informacion.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('namePlayer', models.CharField(max_length=200)),
                ('playerNumber', models.CharField(max_length=5)),
                ('playerPosition', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informacion.teams')),
            ],
        ),
    ]
