# Generated by Django 4.2.7 on 2023-11-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('nombreCiudad', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estadios',
            fields=[
                ('nombreEstadio', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('numEquipo', models.IntegerField()),
                ('nombreEquipo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombreCiudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='micrud.ciudades')),
                ('nombreEstadio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='micrud.estadios')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='nombreEstadio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='micrud.estadios'),
        ),
    ]
