# Generated by Django 4.2.7 on 2023-11-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micrud', '0003_alter_equipos_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='numero',
        ),
        migrations.AlterField(
            model_name='equipos',
            name='numEquipo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
